[Feature][Loewe] Created a logger interceptor for every API endpoints
symphco/symph-libs pull request #7
Opened 2024-05-02 09:20 UTC by mlalivio

2024-05-02 09:20 UTC, symphdevtools commented
Hi! I'm generating PR title and description for you and will automatically apply it to your PR. I'll react :rocket: to this comment when done. Just sit back and chill!

When you have new changes to this PR and you want to regenerate the title and PR description, just comment `churva`!

Let me know if something is not working well, e.g.:
- Some parts of the title and description weren't preserved when generating title and description
- Disappearing screenshots or links
- Etc.

Thanks!

(RIP hatdog)

2024-05-10 08:27 UTC, polens29 approved these changes

2024-05-13 04:41 UTC, johnreyev requested changes, later dismissed
@nik-symph please review as well if you have time

2024-05-13 04:41 UTC, johnreyev commented on logger/src/lib/middlewares/api-logging.middleware.ts
> +      body: responseBody?.toString(),
This is goo @mlalivio , I think we need to whitelist some properties that we shouldn't log e.g. password, pincode, etc.

2024-05-13 05:03 UTC, nik-symph approved these changes

2024-05-28 09:31 UTC, johnreyev approved these changes

2024-05-28 09:36 UTC, merged